#!/usr/bin/env zsh
export ZPLUG_HOME=~/.zplug

. ${ZPLUG_HOME}/init.zsh

zplug "zsh-users/zsh-syntax-highlighting",    nice:10
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-autosuggestions"
zplug "joel-porquet/zsh-dircolors-solarized", hook-load:"setupsolarized dircolors.ansi-universal"
zplug "plugins/git",                          from:oh-my-zsh
zplug "plugins/git-flow",                     from:oh-my-zsh
zplug "plugins/tmux",                         from:oh-my-zsh
zplug "themes/bira",                          from:oh-my-zsh, as:theme
zplug "b4b4r07/enhancd",                      use:init.sh
zplug "junegunn/fzf-bin",                     as:command, from:gh-r, rename-to:fzf
zplug "junegunn/fzf",                         as:command, use:bin/fzf-tmux
zplug "glidenote/hub-zsh-completion"
zplug "b4b4r07/zsh-vimode-visual",            use:"*.sh"
zplug "philovivero/distribution",             as:command, use:distribution, if:'(( $+commands[perl] ))'
zplug "Code-Hex/battery",                     as:command, from:gh-r
zplug "motemen/ghq",                          as:command, from:gh-r,  rename-to:ghq
zplug "monochromegane/the_platinum_searcher", as:command, from:gh-r,  rename-to:"pt",  frozen:1
zplug "stedolan/jq",                          as:command, from:gh-r,  frozen:1

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load --verbose
