#!/usr/bin/env zsh
export ZPLUG_HOME=~/.zplug

. ${ZPLUG_HOME}/init.zsh


zplug "zsh-users/zsh-syntax-highlighting", nice:10
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-autosuggestions"
zplug "joel-porquet/zsh-dircolors-solarized", hook-load:"setupsolarized dircolors.ansi-universal"
alias ls="ls --color=auto"
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}


# Supports oh-my-zsh plugins and the like
zplug "plugins/git",   from:oh-my-zsh
zplug "plugins/tmux",   from:oh-my-zsh

# Also prezto
zplug "modules/prompt", from:prezto, hook-load:"{
	autoload -Uz promptinit
	promptinit
	prompt adam2
}"

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load --verbose

